### ISSUE TITLE
Is it possible to have shared datasets?

### ISSUE THREAD

**Issue by pitanni** [microsoft/RdlMigration#35]
After migration, reports have embedded dataset. It is possible to change (by script or in an automatic way) the embedded dataset in a shared dataset saved in a Power Bi Service?

**Comment by gboreki** [comment]
The powerbi service does not support shared datasets, since there is no equivalent artifact the best conversion is to transform into an embedded dataset. After this conversion you can open the report in Power Bi Report Builder and do further updates.

The closest transformation that would behave similar to a shared dataset would be to use a PowerBi DataSet and then point your report to that dataset. This unfortunately requires a lot of work in the reports.

Thanks
-gboreki
